apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
  labels:
    app: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: index.docker.io/xorfxorf99/calculator-test
        imagePullPolicy: Always
        resources: 
          requests:
            memory: 150Mi
            cpu: 50m
        readinessProbe: 
          httpGet: 
            path: /healthz 
            port: 31002 
          initialDelaySeconds: 30
          timeoutSeconds: 45
        livenessProbe: 
          httpGet: 
            path: /healthz 
            port: 31002 
          initialDelaySeconds: 30
          timeoutSeconds: 45
        ports:
        - containerPort: 8080
        

---

apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  type: NodePort
  selector:
    app: calculator
  ports:
  - port: 8080
    nodePort: 31002
    protocol: TCP
    targetPort: 8080 
    
--- 

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler 
metadata: 
  name: calculator-hpa 
  namespace: default
spec: 
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef: 
    apiVersion: extensions/v1beta1 
    kind: Deployment
    name: calculator-deployment
  targetCPUUtilizationPercentage: 100